spring:
  profiles:
    active: dev

server:
  port: 8761

info:
  app:
    name: DiscoveryService
    description: EHR platform global discovery service
    version: 1.0.0

security:
  user:
    password: eureka

eureka:
  instance:
      hostname: localhost
      prefer-ip-address: true
      #leaseRenewalIntervalInSeconds: 15
      #metadataMap:
            #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    #don't register this app as a service in eureka
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0
      enable-self-preservation: false

  server:
      enable-self-preservation: false
      waitTimeInMsWhenSyncEmpty: 500000

