spring:
  profiles:
    active: dev

server:
  port: 8761

info:
  app:
    name: DiscoveryService
    description: EHR platform global discovery service
    version: 1.0.0

---

spring:
  profiles: dev

security:
  user:
    password: eureka

eureka:
  instance:
      hostname: localhost
      #ipAddress: 127.0.0.1
  client:
    #don't register this app as a service in eureka
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0
      enable-self-preservation: false

    instance:
      hostname: localhost
  server:
      enable-self-preservation: false
      waitTimeInMsWhenSyncEmpty: 0


---

spring:
  profiles: prod