server:
  port: 8761

security:
  user:
    password: eureka

eureka:
  instance:
    preferIpAddress: true

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ipAddress}:${server.port}/eureka/

info:
  app:
    name: DiscoveryService
    description: EHR platform global discovery service
    version: 1.0.0

---
spring:
  profiles: dev

eureka:
  instance:
    ipAddress: 127.0.0.1

---
spring:
  profiles: test

eureka:
  instance:
    ipAddress: 172.19.103.73

---
spring:
  profiles: prod

eureka:
  instance:
    ipAddress: 11.1.2.21