server:
  port: ${svr-archive-security.server.port}

management:
  port: ${server.port}

info:
  app:
    name: ArchiveSecurityApp
    description: Archive Security service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod