server:
  port: ${svr-health-profile-search.server.port}

management:
  port: ${server.port}

info:
  app:
    name: HealthProfileSearchService
    description: EHR platform health profile search service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
