server:
  port: ${svr-security.server.port}

management:
  port: ${server.port}

info:
  app:
    name: SecurityService
    description: EHR platform security service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
