svr-authentication:
  server:
    port: 10260

spring:
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

server:
  port: ${svr-authentication.server.port}
#  ssl:
#    key-store: D:/tomcat.keystore

management:
  port: ${server.port}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47
    #host: 192.168.72.128
    port: 6379
    password: redis!@456
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50871

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    #host: 192.168.72.128
    port: 6379
    password: redis!@456
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50871

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    password: Kb6wKDQP1W4
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50871

---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 10.176.97.5
    port: 6390
    password: q4YaQemf
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50641


---
spring:
  profiles: prod_fzzy
  datasource:
    url: jdbc:mysql://100.100.1.159:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 100.100.1.161
    port: 6390
    password: q4YaQemf
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50641

---
spring:
  profiles: prod_srformal
  datasource:
    url: jdbc:mysql://192.168.40.34:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU
  redis:
    host: 192.168.50.82
    port: 6379
    password: q4YaQemf
#福州总部网关参数配置
fz-gateway:
  url: http://service.yihu.com:8080/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  handlerId: 50641