discovery:
  image: discovery:ehr
  environment: spring.profiles.actve:default,test
  expose: 8761
  ports:
   - 8761:8761

config:
  image: config:ehr
  expose: 1221
  ports:
     - 1221:1221
  links:
   - discovery

svr-dict:
  image: svr-dict:ehr
  ports:
     - 10050:10050
  links:
   - discovery
   - config

svr-geography:
  image: svr-geography:ehr
  ports:
     - 10090:10090
  links:
   - discovery
   - config
   - svr-dict

svr-app:
  image: svr-app:ehr
  ports:
     - 10080:10080
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography

svr-organization:
  image: svr-organization:ehr
  ports:
     - 10170:10170
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app

svr-patient:
  image: svr-patient:ehr
  ports:
     - 10100:10100
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app
   - svr-organization

svr-security:
  image: svr-security:ehr
  ports:
     - 10110:10110
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app
   - svr-organization
   - svr-patient

svr-user:
  image: svr-user:ehr
  ports:
     - 10120:10120
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app
   - svr-organization
   - svr-security
   - svr-patient

svr-esb:
  image: svr-esb:ehr
  ports:
     - 10130:10130
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app
   - svr-organization
   - svr-security
   - svr-patient
   - svr-user

svr-resource:
  image: svr-resource:ehr
  ports:
     - 10140:10140
  links:
   - discovery
   - config
   - svr-dict
   - svr-geography
   - svr-app
   - svr-organization