server:
  port: ${svr-health-profile.server.port}

management:
  port: ${server.port}

info:
  app:
    name: BrowserService
    description: EHR platform health profile service.
    version: 1.0.0
  component: Zuul Server

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 120000
---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
