server:
  port: ${svr-health-profiles.server.port}

management:
  port: ${server.port}

info:
  app:
    name: BrowserService
    description: EHR platform health profile service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
