##如果有配置服务的话，远程服务器和本地服务器配置不一致的情况下，优先远程的为主  git上 svr-base ->  git application ->本地 appliction ->本地 bootstarp
server:
  port: ${svr-quota.server.port}

management:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

hadoop:
  hbase-properties:
    - hbase.zookeeper.property.clientPort: 2181
    - zookeeper.znode.parent: /hbase-unsecure
    - hbase.zookeeper.quorum: node1,node2,node3
  user:
    name: root

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: chenweishan
    password: chenweishan

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.

---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: weifuwu
    password: weifuwu

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.


---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
    username: ha
    password: jkzlxm

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.



---
spring:
  profiles: prod_sr

  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
    username: healthcloud
    password: GP8Qz4qU

  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com:2181/solr # ZooKeeper host address in the form HOST:PORT.

