server:
  port: 10140

management:
  port: ${server.port}

info:
  app:
    name: JsonPackageService
    description: EHR platform package service.
    version: 1.1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:eureka@${eureka-server-ip}/eureka/

---
spring:
  profiles: dev

eureka-server-ip: 127.0.0.1:8761

---
spring:
  profiles: test

eureka-server-ip: 172.19.103.73:8761

---
spring:
  profiles: prod

eureka-server-ip: 11.1.2.21:8761