server:
  port: ${svr-resource.server.port}

management:
  port: ${server.port}

info:
  app:
    name: ResourceServiceApp
    description: Resource service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod