server:
  port: 10140

management:
  port: 10140

info:
  app:
    name: ResourceServiceApp
    description: Resource service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
