server:
  port: 10150

#security:
#  user:
#    password: adaption

info:
  app:
    name: AdaptionService
    description: EHR platform adaption service.
    version: 1.0.0


ehr:
  common:
    invalid:
      parameter: 参数解析错误！
    query:
      not:
        found: 不存在该对象！
  commons:
    repeat:
      code: 代码重复！
---

spring:
  profiles: dev

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/


---
spring:
  profiles: test

eureka:
  instance:
    hostname: 192.168.131.151
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@192.168.131.151:8761}/eureka/

---
spring:
  profiles: prod

eureka:
  instance:
    hostname: 11.1.2.21
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@11.1.2.21:8761}/eureka/

