/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yihu.ehr.profile;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-15")
public class TEhrRecord implements org.apache.thrift.TBase<TEhrRecord, TEhrRecord._Fields>, java.io.Serializable, Cloneable, Comparable<TEhrRecord> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TEhrRecord");

  private static final org.apache.thrift.protocol.TField META_DATAS_FIELD_DESC = new org.apache.thrift.protocol.TField("metaDatas", org.apache.thrift.protocol.TType.MAP, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TEhrRecordStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TEhrRecordTupleSchemeFactory());
  }

  public Map<String,String> metaDatas; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    META_DATAS((short)1, "metaDatas");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // META_DATAS
          return META_DATAS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.META_DATAS, new org.apache.thrift.meta_data.FieldMetaData("metaDatas", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TEhrRecord.class, metaDataMap);
  }

  public TEhrRecord() {
  }

  public TEhrRecord(
    Map<String,String> metaDatas)
  {
    this();
    this.metaDatas = metaDatas;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TEhrRecord(TEhrRecord other) {
    if (other.isSetMetaDatas()) {
      Map<String,String> __this__metaDatas = new HashMap<String,String>(other.metaDatas);
      this.metaDatas = __this__metaDatas;
    }
  }

  public TEhrRecord deepCopy() {
    return new TEhrRecord(this);
  }

  @Override
  public void clear() {
    this.metaDatas = null;
  }

  public int getMetaDatasSize() {
    return (this.metaDatas == null) ? 0 : this.metaDatas.size();
  }

  public void putToMetaDatas(String key, String val) {
    if (this.metaDatas == null) {
      this.metaDatas = new HashMap<String,String>();
    }
    this.metaDatas.put(key, val);
  }

  public Map<String,String> getMetaDatas() {
    return this.metaDatas;
  }

  public TEhrRecord setMetaDatas(Map<String,String> metaDatas) {
    this.metaDatas = metaDatas;
    return this;
  }

  public void unsetMetaDatas() {
    this.metaDatas = null;
  }

  /** Returns true if field metaDatas is set (has been assigned a value) and false otherwise */
  public boolean isSetMetaDatas() {
    return this.metaDatas != null;
  }

  public void setMetaDatasIsSet(boolean value) {
    if (!value) {
      this.metaDatas = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case META_DATAS:
      if (value == null) {
        unsetMetaDatas();
      } else {
        setMetaDatas((Map<String,String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case META_DATAS:
      return getMetaDatas();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case META_DATAS:
      return isSetMetaDatas();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TEhrRecord)
      return this.equals((TEhrRecord)that);
    return false;
  }

  public boolean equals(TEhrRecord that) {
    if (that == null)
      return false;

    boolean this_present_metaDatas = true && this.isSetMetaDatas();
    boolean that_present_metaDatas = true && that.isSetMetaDatas();
    if (this_present_metaDatas || that_present_metaDatas) {
      if (!(this_present_metaDatas && that_present_metaDatas))
        return false;
      if (!this.metaDatas.equals(that.metaDatas))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_metaDatas = true && (isSetMetaDatas());
    list.add(present_metaDatas);
    if (present_metaDatas)
      list.add(metaDatas);

    return list.hashCode();
  }

  @Override
  public int compareTo(TEhrRecord other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMetaDatas()).compareTo(other.isSetMetaDatas());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetaDatas()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metaDatas, other.metaDatas);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TEhrRecord(");
    boolean first = true;

    sb.append("metaDatas:");
    if (this.metaDatas == null) {
      sb.append("null");
    } else {
      sb.append(this.metaDatas);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TEhrRecordStandardSchemeFactory implements SchemeFactory {
    public TEhrRecordStandardScheme getScheme() {
      return new TEhrRecordStandardScheme();
    }
  }

  private static class TEhrRecordStandardScheme extends StandardScheme<TEhrRecord> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TEhrRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // META_DATAS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.metaDatas = new HashMap<String,String>(2*_map0.size);
                String _key1;
                String _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readString();
                  _val2 = iprot.readString();
                  struct.metaDatas.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setMetaDatasIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TEhrRecord struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.metaDatas != null) {
        oprot.writeFieldBegin(META_DATAS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.metaDatas.size()));
          for (Map.Entry<String, String> _iter4 : struct.metaDatas.entrySet())
          {
            oprot.writeString(_iter4.getKey());
            oprot.writeString(_iter4.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TEhrRecordTupleSchemeFactory implements SchemeFactory {
    public TEhrRecordTupleScheme getScheme() {
      return new TEhrRecordTupleScheme();
    }
  }

  private static class TEhrRecordTupleScheme extends TupleScheme<TEhrRecord> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TEhrRecord struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMetaDatas()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMetaDatas()) {
        {
          oprot.writeI32(struct.metaDatas.size());
          for (Map.Entry<String, String> _iter5 : struct.metaDatas.entrySet())
          {
            oprot.writeString(_iter5.getKey());
            oprot.writeString(_iter5.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TEhrRecord struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map6 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.metaDatas = new HashMap<String,String>(2*_map6.size);
          String _key7;
          String _val8;
          for (int _i9 = 0; _i9 < _map6.size; ++_i9)
          {
            _key7 = iprot.readString();
            _val8 = iprot.readString();
            struct.metaDatas.put(_key7, _val8);
          }
        }
        struct.setMetaDatasIsSet(true);
      }
    }
  }

}

