server:
  port: 10320

logging:
  level:
    root: INFO

kafka:
  broker:
    address: node1.hde.h3c.com:6667

zookeeper:
  broker:
    address: node1.hde.h3c.com:2181,node2.hde.h3c.com:2181

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu


service-gateway:
  username: user
  password: eureka
  url: http://192.168.1.221:10000/api/v1.0/admin

kafka:
  broker:
    address: node1.hde.h3c.com:6667

es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host:  http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl


---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu

service-gateway:
  username: user
  password: eureka
  url: http://192.168.1.221:10000/api/v1.0/admin

kafka:
  broker:
    address: node1.hde.h3c.com:6667

es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host:  http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl


---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.77/wlyy?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456

service-gateway:
  username: user
  password: eureka
  url: http://192.168.135.31:10000/api/v1.0/admin

kafka:
  broker:
    address: node1.hde.h3c.com:6667

es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host:  http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl


---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU

service-gateway:
  username: user
  password: eureka
  url: http://11.1.2.13:10000/api/v1.0/admin

kafka:
  broker:
    address: 11.1.2.21:6667


---
spring:
  profiles: prod_sr
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU


service-gateway:
  username: user
  password: eureka
  url: http://10.176.97.10:10000/api/v1.0/admin

kafka:
  broker:
    address: 10.176.97.7:6667