server:
  port: ${svr-log-collection.server.port}

logging:
  level:
    root: INFO
#kafka:
 # broker:
  #  address: node1.hde.h3c.com:6667
#zookeeper:
 # broker:
  #  address: node1.hde.h3c.com:2181,node2.hde.h3c.com:2181
spring:
  session:
    store-type: none
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
service-gateway:
  username: user
  password: eureka
  url: http://192.168.1.221:10000/api/v1.0/admin
kafka:
  broker:
    address: node1.hde.h3c.com:6667
zookeeper:
  broker:
    address: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com:2181
