server:
  port: 10040

management:
  port: ${server.port}

info:
 app:
   name: StandardService
   description: EHR platform standard service.
   version: 1.0.0

ehr:
 commons:
   repeat:
     code: 代码已存在!

common:
 query:
   not:
     found: 该{0}不存在：{1}
   miss:
     parameter:  参数不能为空：{0}！
   notfound:
     entity: 没有找到{0}实体：{}
std:
 version:
   invalid:
     stage: 该版本不处于编辑状态！

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:eureka@${eureka-server-ip}/eureka/

---
spring:
  profiles: dev

eureka-server-ip: 127.0.0.1:8761

---
spring:
  profiles: test

eureka-server-ip: 172.19.103.73:8761

---
spring:
  profiles: prod

eureka-server-ip: 11.1.2.21:8761