server:
  port: ${svr-standard.server.port}

management:
  port: ${server.port}

info:
 app:
   name: StandardService
   description: EHR platform standard service.
   version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
