server:
  port: 10040

#security:
#  user:
#    password: standard

info:
  app:
    name: StandardService
    description: EHR platform standard service.
    version: 1.0.0

ehr:
  commons:
    repeat:
      code: 代码已存在!
  common:
    query:
      not:
        found: 该{0}不存在：{1}
    miss:
      parameter:  参数不能为空：{0}！
    notfound:
      entity: 没有找到{0}实体：{}
  std:
    version:
      invalid:
        stage: 该版本不处于编辑状态！

---
spring:
  profiles: dev

eureka:
  instance:
    address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

hibernate:
  show-sql: true
  format-sql: true

fast-dfs:
  tracker-server: 172.19.103.54:22122
---
spring:
  profiles: test

eureka:
  instance:
    ip-address: 172.19.103.73
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/

data-source:
  url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: yuhaihua
  password: yuhaihua

hibernate:
  show-sql: true
  format-sql: true

fast-dfs:
  tracker-server: 172.19.103.54:22122
---server:
     port: 10040

   #security:
   #  user:
   #    password: standard

   info:
     app:
       name: StandardService
       description: EHR platform standard service.
       version: 1.0.0

   ehr:
     commons:
       repeat:
         code: 代码已存在!
     common:
       query:
         not:
           found: 该{0}不存在：{1}
       miss:
         parameter:  参数不能为空：{0}！
       notfound:
         entity: 没有找到{0}实体：{}
     std:
       version:
         invalid:
           stage: 该版本不处于编辑状态！

   ---
   spring:
     profiles: dev

   eureka:
     instance:
       address: localhost
     client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/


   ---
   spring:
     profiles: test

   eureka:
     instance:
       ip-address: 172.19.103.73
     client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/


   ---
   spring:
     profiles: prod

   eureka:
     instance:
       hostname: 11.1.2.21
     client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@11.1.2.21:8761}/eureka/


spring:
  profiles: prod

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

