server:
  port: ${svr-user.server.port}

management:
  port: ${server.port}

info:
  app:
    name: UserService
    description: EHR platform user service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
