server:
  port: ${svr-user.server.port}

management:
  port: ${server.port}

info:
  app:
    name: UserService
    description: EHR platform user service.
    version: 1.0.0

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30
  charset: ISO8859-1
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

---
spring:
  profiles: dev

fast-dfs:
  tracker-server: 172.19.103.54:22122

---
spring:
  profiles: test

---
spring:
  profiles: prod
