server:
  port: 10150

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
  redis:
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1
  kafka:
    consumer:
      group-id: svr-pack-event
      auto-offset-reset: earliest

fast-dfs:
  connect-timeout: 20
  network-timeout: 60
  charset: ISO8859-1
  pool:
    init-size: 10
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

hadoop:
  hbase-properties:
    hbase.zookeeper.property.clientPort: 2181
    zookeeper.znode.parent: /hbase-unsecure
  user:
    name: root

elasticsearch:
  pool:
    init-size: 5
    max-size: 10

event:
  job:
    init-size: 10 #事件处理初始任务数
    max-size: 10 #事件处理最大任务数
    cron-exp: 0/1 * * * * ? #事件处理任务触发间隔表达式

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  kafka:
    bootstrap-servers: debian-1:9092
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52
hadoop:
  hbase-properties:
    hbase.zookeeper.quorum: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  kafka:
    bootstrap-servers: debian-1:9092
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52
hadoop:
  hbase-properties:
    hbase.zookeeper.quorum: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300