server:
  port: ${svr-redis.server.port}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time