server:
  port: ${svr-redis.server.port}

management:
  port: ${server.port}

logging:
  level:
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    port: 6379 # Redis server port.
    password: # Login password of the redis server.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.

    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true


fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  connect-timeout: 2
  network-timeout: 30
  charset: ISO8859-1
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

hystrix:
  threadpool:
    default:
      coreSize: 50 #并发执行的最大线程数，默认10
      maxQueueSize: 100 #LinkedBlockingQueue的最大队列数，默认-1，使用SynchronousQueue
      #queueSizeRejectionThreshold: 50 #配置该值后，即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000 #缺省为1000
---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan

  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456

fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
# 由于生产环境服务器维护通过堡垒机管理，不允许代码直接通过SSH访问远程服务器。
# 暂时注释，寻求别的方法再去掉。
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22

---
spring:
  profiles: alpha

  datasource:
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ha
    password: ha

  redis:
    host: 192.168.1.220 # Redis server host.

fast-dfs:
  tracker-server: 172.19.103.54:22122
  public-server: http://172.19.103.54:22122
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22



---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu

  redis:
    host: 172.19.103.47 # Redis server host.

fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22



---
spring:
  profiles: prod

  redis:
    host: 11.1.2.20 # Redis server host.
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ha
    password: jkzlxm

fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://ds.ehr.yihu.com:22122
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22

---
spring:
  profiles: prod_fz
  datasource:
    url: jdbc:mysql://11.1.2.5:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU

  redis:
    host: 11.1.2.22 # Redis server host.
    port: 6390
    # Login password of the redis server.
    password: Kb6wKDQP1W4
fast-dfs:
  tracker-server: 11.1.2.9:22122
  public-server: http://11.1.2.9:80
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22

---
spring:
  profiles: prod_sr

  redis:
    host: 10.176.97.5 # Redis server host.
    port: 6390
    password: q4YaQemf
  datasource:
    url: jdbc:mysql://10.176.97.9:3310/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: healthcloud
    password: GP8Qz4qU

fast-dfs:
  tracker-server: 10.176.97.5:22122
  public-server: http://10.176.97.5:8888
ehr-redis:
  mq:
    pubsub:
      publisherAppId: svr-redis
      responseTimeChannel: redis.cache.reponse-time
  cache:
    memory:
      rdbFilePath: /usr/local/bin/dump.rdb
      outFilePath: /usr/local/ehr/redisReport/memory.csv
#  server:
#    host: 172.19.103.47
#    username: root
#    password: jkzl
#    ssh-port: 22