/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yihu.ehr.data.domain;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 排序方向
 * 
 */
public enum TDirection implements org.apache.thrift.TEnum {
  ASC(1),
  DESC(2);

  private final int value;

  private TDirection(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TDirection findByValue(int value) { 
    switch (value) {
      case 1:
        return ASC;
      case 2:
        return DESC;
      default:
        return null;
    }
  }
}
