server:
  port: ${svr-esb.server.port}

management:
  port: ${server.port}

info:
  app:
    name: simplifiedESB
    description: EHR platform simplifiedESB service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
