server:
  port: 10001

management:
  port: ${server.port}

info:
  app:
    name: AdaptionService
    description: EHR platform adaption service.
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.220:8761/eureka/

spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: false
