server:
  port: ${svr-profile-statistics.server.port}

management:
  port: ${server.port}

info:
  app:
    name: ProfileStatisticsApp
    description: Profile Statistics service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod