server:
  port: ${svr-pack-resolve.server.port}

management:
  port: ${server.port}

info:
  app:
    name: JsonPackageService
    description: EHR platform json package resolve service, resolve package to hbase.
    version: 1.1.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
