server:
  port: ${svr-pack-resolve.server.port}

management:
  port: ${server.port}

info:
  app:
    name: PackageResolveService
    description: EHR platform package resolve service.
    version: 1.1.0

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 120000

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
