server:
  port: 10210

management:
  port: ${server.port}

info:
  app:
    name: PictureService
    description: EHR platform picture service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

