server:
  port: 1221

security:
  user:
    password: configuration

endpoints:
  restart:
    enabled: true

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

---
spring:
  profiles: dev

  cloud:
    config:
      server:
        git:
          uri: C:\Users\Administrator\Desktop\103环境\ehr.config
        default-label: dev

eureka:
  instance:
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@localhost:8761}/eureka/

---
spring:
  profiles: test

  cloud:
    config:
      server:
        git:
          uri:
        default-label:

eureka:
  instance:
    ip-address:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:

---
spring:
  profiles: prod

  cloud:
    config:
      server:
        git:
          uri:
        default-label:

eureka:
  instance:
    ip-address:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: