server:
  port: 1221

management:
  port: ${server.port}

security:
  user:
    password: configuration

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

---
spring:
  profiles: dev

eureka:
  instance:
    ip-address: 127.0.0.1:8761
    prefer-ip-address: true

---
spring:
  profiles: test

eureka:
  instance:
    ip-address: 172.19.103.73:8761
    prefer-ip-address: true

---
spring:
  profiles: prod_fz

eureka:
  instance:
    ip-address: 11.1.2.1:8761
    prefer-ip-address: true

---
spring:
  profiles: prod_sr

eureka:
  instance:
    ip-address: 10.176.97.10:8761
    prefer-ip-address: true


---
spring:
  profiles: prod_fzzy

eureka:
  instance:
    ip-address: 100.100.1.162:8761
    prefer-ip-address: true

---
spring:
  profiles: prod_srformal

eureka:
  instance:
    ip-address: 192.168.200.61:8761
    prefer-ip-address: true