server:
  port: 1221

security:
  user:
    password: configuration

endpoints:
  restart:
    enabled: true

info:
  app:
    name: ConfigurationService
    description: EHR平台全局配置服务
    version: 1.0.0

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.220:10080/EHR/ehr.config.git
        default-label: dev

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: sand-home-dev
  cloud:
    config:
      server:
        git:
          uri: file://D:/Workspace/ehr.config
        default-label: dev

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.220:10080/EHR/ehr.config.git
        default-label: dev

eureka:
  instance:
    ip-address: 192.168.131.151
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@192.168.131.151:8761}/eureka/

---
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: http://11.1.2.8:3000/ehr_admin/ehr.config.git
        default-label: master

eureka:
  instance:
    ip-address: 11.1.2.21
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@11.1.2.21:8761}/eureka/