server:
  port: 1221

management:
  port: ${server.port}

security:
  user:
    password: configuration

info:
  app:
    name: ConfigurationService
    description: EHR平台全局配置服务
    version: 1.0.0

---
spring:
  profiles: dev

eureka:
  instance:
    ip-address: 127.0.0.1:8761
    #ip-address: 192.168.1.221:8761
    prefer-ip-address: true

---
spring:
  profiles: alpha

eureka:
  instance:
    ip-address: 172.19.103.11:8761
    prefer-ip-address: true

---
spring:
  profiles: test

eureka:
  instance:
    ip-address: 172.19.103.73:8761
    prefer-ip-address: true

---
spring:
  profiles: prod

eureka:
  instance:
    ip-address: 11.1.2.21:8761
    prefer-ip-address: true

---
spring:
  profiles: prod_fz

eureka:
  instance:
    ip-address: 192.168.135.29:8761
    prefer-ip-address: true