server:
  port: 1221

management:
  port: ${server.port}

security:
  user:
    password: configuration

info:
  app:
    name: ConfigurationService
    description: EHR平台全局配置服务
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod