server:
  port: 1221

security:
  user:
    password: configuration

endpoints:
  restart:
    enabled: true

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.220:10080/EHR/ehr.config.git
        default-label: dev

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: sand-home-dev
  cloud:
    config:
      server:
        git:
          uri: file://D:/Workspace/ehr.config
        default-label: dev

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.220:10080/EHR/ehr.config.git
        default-label: dev

eureka:
  instance:
    ip-address: 172.19.103.73
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/