server:
  port: 1221

management:
  port: ${server.port}

security:
  user:
    password: configuration

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
