server:
  port: 1221

security:
  user:
    password: configuration

endpoints:
  restart:
    enabled: true

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

---
spring:
  profiles: dev

  cloud:
    config:
      server:
        git:
<<<<<<< HEAD
          #uri: http://192.168.1.103:9000/EHR/ehr.config/
          uri: file:C:/Users/Administrator/Desktop/103环境/ehr.config
=======
          uri: http://192.168.1.103:9000/EHR/ehr.config
>>>>>>> fbb09dacbc9e960a2b7959ca33ad3996c68f27f1
        default-label: dev

eureka:
  instance:
    ip-address: 192.168.1.220
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@192.168.1.220:8761}/eureka/

---
spring:
  profiles: test

  cloud:
    config:
      server:
        git:
          uri:
        default-label:

eureka:
  instance:
    ip-address:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:

---
spring:
  profiles: prod

  cloud:
    config:
      server:
        git:
          uri:
        default-label:

eureka:
  instance:
    ip-address:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: