server:
  port: ${ag-admin.server.port}

management:
  port: ${server.port}

info:
  app:
    name: AgAdminService
    description: EHR platform json app service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

