server:
  port: 10000

management:
  port: ${server.port}

info:
  app:
    name: AgAdminService
    description: EHR platform json app service.
    version: 1.0.0
  component: Zuul Server


ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 6000

zuul:
  ignored-services: "*"
  routes:
    svr-adaption: /api/v1.0/adapter/plan/adapterDataSet

---
spring:
  profiles: lincl

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000
---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

