server:
  port: ${ag-admin.server.port}

info:
  app:
    name: AG-ADMIN
    description: EHR Platform Gateway Service
    version: 1.0.0
  component: Zuul Server

eip:
  tenant: jkzl

zuul:
  ignored-services: '*'
  routes:
    svr-dfs:
      path: /dfs/**
      serviceId: svr-dfs
    svr-basic:
      path: /basic/**
      serviceId: svr-basic
    svr-quota:
      path: /quota/**
      serviceId: svr-quota
    svr-redis:
      path: /redis/**
      serivceId: svr-redis
    svr-resource:
      path: /resource/**
      serviceId: svr-resource
    svr-standard:
      path: /standard/**
      serviceId: svr-standard
    svr-authentication:
      path: /authentication/**
      serviceId: svr-authentication
    svr-health-profile:
      path: /profile/**
      serviceId: svr-health-profile
    svr-pack-analyzer:
      path: /pack-analyzer/**
      serviceId: svr-pack-analyzer
    svr-pack-mgr:
      path: /pack-mgr/**
      serviceId: svr-pack-mgr
    svr-pack-resolv:
      path: /pack-resolve/**
      serviceId: svr-pack-resolve
    hos-admin:
      path: /hos-admin/**
      serviceId: hos-admin

---
spring:
  profiles: dev
#总部统一网关接口参数配置
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0
zuul:
  routes:
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/

---
spring:
  profiles: prod
#总部统一网关接口参数配置
service-gateway:
  url: http://service.yihu.com:8085/WSGW/rest
  handlerId: 50871
  clientId: 9000401
  clientVersion: 1.0
zuul:
  routes:
    fastdfs-server:
      path: /file/**
      url: http://172.19.103.52:80/
