server:
  port: 1221

security:
  user:
    password: configuration

endpoints:
  restart:
    enabled: true

info:
  app:
    name: ConfigurationService
    description: EHR platform global configuration service
    version: 1.0.0

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: file://D:/Workspace/source/spring.cloud.config.ehr
        default-label: master

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: file://D:/Workspace/source/spring.cloud.config.ehr
        default-label: master

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@192.168.1.200:8761}/eureka/

---
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: file://D:/Workspace/source/spring.cloud.config.ehr
        default-label: master

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@10.11.12.13:8761}/eureka/