server:
  port: ${svr-basic.server.port}
eip:
  tenant: jkzl
  #健康上饶app-卫计委机构编码--用于居民注册设置默认权限
jksr-app:
  orgcode: PDY026797
  registerRoleClientId: WYo0l73F8e,HPnz4GXfYA #用于创建这些应用的默认角色(健康上饶app，公众健康服务)

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  data:
    mongodb:
      host: 192.168.1.220
      port: 27017
      username: admin
      password: admin
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.19.103.68:9200
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl
h5:
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://172.19.103.73:10001/fzGateway/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  handlerId: 50871

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  # -- unknown use --
  ldap:
    host: 172.19.103.87
    port: 389
    bindDn: cn=admin,dc=ehr,dc=jkzl
    password: jkzl
    root: dc=ehr,dc=jkzl
  # -- unknown use --
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  data:
    mongodb:
      host: 192.168.1.220
      port: 27017
      username: admin
      password: admin
      authenticationDatabase: admin
      database: ehr
  elasticsearch:
    jest:
      uris: http://172.19.103.68:9200
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
es:
  index: wlyy_quota_test
  type: wlyy_quota_test
  host: http://172.19.103.68:9200
  tHost: 172.19.103.68:9300
  clusterName: jkzl
h5:
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  appId: 9000401
  clientId: WYo0l73F8e
#福州总部网关参数配置
fz-gateway:
  url: http://172.19.103.73:10001/fzGateway/WSGW/rest
  clientId: 9000401
  clientVersion: 1.0
  secret: KU5XTORDKZI3O86YAT3ABCNJW2XTL1DJYF3GKU3ICXL
  handlerId: 50871