server:
  port: ${svr-portal.server.port}

management:
  port: ${server.port}

info:
  app:
    name: AppService
    description: EHR platform open service applicate administrative service.
    version: 1.0.0

---
spring:
  profiles: dev
#  本地微服务启动配置
#  datasource:
#    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
#    username: ha
#    password: ha
#
#fast-dfs:
#  tracker-server: 172.19.103.54:22122
#  public-server: http://172.19.103.54:22122

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
