server:
  port: ${svr-dfs.server.port}

elasticsearch:
  pool:
    init-size: 2
    max-size: 5

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80