server:
  port: ${svr-pack-resolve.server.port}

resolve:
  job:
    init-size: 10 #解析入库初始任务数
    max-size: 10 #解析入库最大任务数
    cron-exp: 0/1 * * * * ? #解析任务触发间隔表达式

elasticsearch:
  pool:
    init-size: 10
    max-size: 20

ehr:
  # 档案包数据提取器参数，从数据集中提取摘要、事件时间与身份标识
  pack-extractor:
    # 事件提取参数,用于生成事件摘要
    # 门诊从“门诊摘要”与“挂号”数据集提取事件
    # 住院从“病人摘要”，“入院记录”与“病案首页”提取事件 Clinic 0门诊 Resident 1住院  MedicalExam 2体检
    event:
      data-sets:
        - HDSC01_02: Clinic #门诊-挂号 v1.0
        - HDSD00_85: Clinic #门诊-挂号 v1.3
        - HDSB03_10: Clinic #门诊-传染病报告卡信息 v1.3
        - HDSC02_09: Resident #住院-入院记录 v1.0
        - HDSD00_13: Resident #住院-入院记录 v1.3
        - HDSD00_16: Resident #住院-出院小结 v1.3
        - HDSB05_03: MedicalExam #体检-登记信息 v1.3
    #诊断信息
    diagnosis:
      data-sets:
        - HDSC01_03 #门诊-诊断记录 v1.0
        - HDSD00_73 #门诊-诊断记录 v1.3
        - HDSC02_17 #住院-诊断记录 v1.0
        - HDSD00_69 #住院-诊断记录 v1.3
        - HDSB05_84 #体检-诊断记录 v1.3
      code-meta-data:
        - HDSD00_01_550 #门诊-疾病临床诊断在特定分类体系中的代码 v1.0 & v1.3
        - HDSD00_69_002 #住院-疾病临床诊断在特定分类体系中的代码 v1.3
        - JDSB05_84_003 #体检-疾病临床诊断在特定分类体系中的代码 v1.3
      name-meta-data:
        - HDSD00_01_549 #门诊-疾病临床诊断在特定分类体系中的名称 v1.0 & v1.3
        - HDSD00_69_001 #住院-疾病临床诊断在特定分类体系中的名称 v1.3
        - JDSB05_84_004 #体检-疾病临床诊断在特定分类体系中的名称 v1.3
    #身份提取参数，从人口学提取
    identity:
      data-sets:
        - HDSA00_01 #人口学信息 v1.0 & v1.3
      meta-data:
        id-card-no: HDSA00_01_017 #身份证号码 v1.0 & v1.3
        id-card-type: HDSA00_01_016 #身份证类型 v1.0 & v1.3
        patient-name: HDSA00_01_009 #本人姓名 v1.3 (v1.0:HDSD00_01_002)
        patient-sex: HDSA00_01_011 #性别代码
        birthday: HDSA00_01_012 #出生日期
    #卡提取参数，从就诊摘要提取
    card:
      data-sets:
        - HDSC01_02 #门诊-挂号 v1.0
        - HDSD00_85 #门诊-挂号 v1.3
        - HDSC02_09 #住院-入院记录 v1.0
        - HDSD00_13 #住院-入院记录 v1.3
      card-num:
        - JDSD00_85_005 #门诊-就诊卡号 CARD_NUM
        - JDSD00_13_006 #住院-就诊卡号 CARD_NUM
      card-type:
        - JDSD00_85_006 #门诊-就诊卡类型 CARD_TYPE
        - JDSD00_13_007 #住院-就诊卡类型 CARD_TYPE
    #科室信息
    dept:
      data-sets:
        - HDSD00_85 #门诊-挂号 v1.3
        - HDSD00_13 #住院-入院记录 v1.3
      meta-data:
        - JDSD00_85_001 #门诊-就诊科室代码
        - JDSD00_13_004 #住院-入院科室编码
  #病人事件索引信息
  eventIndex:
    patientId:
      - JDSA00_01_001 #v1.3
      - PATIENT_ID
    eventNo:
      - HDSD00_02_040 #门（急）诊号 v1.3
      - HDSD00_02_066 #住院号 v1.3
      - HDSD03_01_031 #门诊号（挂号） v1.0
      - HDSD00_01_579 #住院号v1.0 会诊记录表编号v1.3
      - EVENT_NO
    eventTime:
      - HDSD00_01_457 #就诊日期时间 v1.0 & v1.3
      - HDSD00_16_031 #入院时间 v1.0
      - HDSD00_13_057 #入院日期时间 v1.3
      - HDSD00_01_185 #出院日期 v1.0
      - HDSD00_16_005 #出院日期时间 v1.3
#error code and message
eip:
  schemaVersion: 5a6951bff0bb

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
  pacs-group-name: group1 # 影像文件落入到group1上

hadoop:
  hbase-properties:
    hbase.zookeeper.quorum: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
ftp:
  address: 172.19.103.58
  username: pacs
  password: pacssr2018
  port: 21

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80
  pacs-group-name: group1 # 影像文件落入到group1上
hadoop:
  hbase-properties:
    hbase.zookeeper.quorum: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300
ftp:
  address: 172.19.103.58
  username: pacs
  password: pacssr2018
  port: 21

