server:
  port: ${svr-dict.server.port}

management:
  port: ${server.port}

info:
  app:
    name: SystemDictionaryService
    description: EHR platform system dictionary service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
