server:
  port: ${svr-standard.server.port}

info:
 app:
   name: StandardService
   description: EHR platform standard service.
   version: 1.0.0
      
common.query.not.found: 该{0}不存在：{1}
common.miss.parameter: 参数不能为空：{0}！
common.notfound.entity: 没有找到{0}实体：{}
std.version.invalid.stage: 该版本不处于编辑状态！

fast-dfs:
  connect-timeout: 2
  network-timeout: 30
  charset: ISO8859-1
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

spring:
  # REDIS
  redis:
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true

eip:
  tenant: jkzl

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    #host: 172.17.110.193
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: weifuwu
    password: weifuwu
  redis:
    host: 172.19.103.47
    port: 6379
    password: redis!@456
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52:80

