server:
  port: 0

security:
  user:
    password: demo

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

info:
  app:
    name: DemoService
    description: EHR micro service demo
    version: 1.0.0
spring:
  config:
    location:
    name: redis