server:
  port: ${svr-special-dict.server.port}

management:
  port: ${server.port}

info:
  app:
    name: SpecialDictService
    description: EHR platform special dictionary service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod