server:
  port: ${svr-special-dict.server.port}

management:
  port: ${server.port}

info:
  app:
    name: SpecialDictService
    description: EHR platform special dictionary service.
    version: 1.0.0

spring:
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    port: 6379 # Redis server port.
    password: # Login password of the redis server.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.

    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.


---
spring:
  profiles: dev
  redis:
      host: 192.168.1.220 # Redis server host.

---
spring:
  profiles: test

---
spring:
  profiles: prod