server:
  port: ${ag-ehr-cloud.server.port}
#  ssl:
#    key-store-password: 123456
#    key-password: 123456

management:
  port: ${server.port}

---
spring:
  profiles: dev
eip:
  tenant: jkzl
---
spring:
  profiles: test
eip:
  tenant: jkzl
---
spring:
  profiles: prod_fz
eip:
  tenant: jkzl
---
spring:
  profiles: prod_sr
eip:
  tenant: jkzl
---
spring:
  profiles: prod_fzzy
eip:
  tenant: jkzl