spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
    username: ha
    password: ha

server:
  port: ${ag-ehr-cloud.server.port}
#  ssl:
#    key-store: C:/Windows/tomcat.keystore

management:
  port: ${server.port}



---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
