server:
  port: ${ag-ehr-cloud.server.port}
  ssl:
    key-store: C:/Windows/tomcat.keystore
management:
  port: ${server.port}

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
