#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&amp;characterEncoding=UTF-8
#    username: ha
#    password: ha
#    driver-class: com.mysql.jdbc.Driver

#spring:
#  view:
#    prefix: /WEB-INF/ehr/jsp/
#    suffix: .jsp
#

server:
#  contextPath: /ehr
  port: 8080

service-gateway:
  username: user
  password: eureka
  url: http://localhost:10000/api/v1.0/admin
  stdurl: http://localhost:10000/api/v1.0/admin/std
  versionurl: http://localhost:10000/api/v1.0/admin/version
  cdatypeurl: http://localhost:10000/api/v1.0/admin/cda_type
  stdsourceurl: http://localhost:10000/api/v1.0/admin/standard_source


#  hopurl: http://172.19.103.55:8080/WSGW/services/ServiceGateWay
#  org_code: 41872607-9
#  module: api
#  #serverip: 192.168.131.1
#  serverip: localhost
#  port: 10000
#  version: v1.0

fast-dfs:
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500

  connect-timeout: 2
  network-timeout: 30

  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

  tracker-server: 172.19.103.54:22122