server:
  port: 10120

management:
  port: ${server.port}

info:
  app:
    name: GeographyService
    description: EHR platform json geography service.
    version: 1.0.0


data-source:
  driver-class-name: com.mysql.jdbc.Driver
  initialize-size: 1
  max-total: 20
  max-idle: 10
  min-idle: 1
  validation-query: SELECT 1
  test-on-borrow: true
  remove-abandoned-timeout: 55

deploy:
  region: 3502

---

spring:
  profiles: lincl
data-source:
  url: jdbc:mysql://192.168.1.220:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8
  user-name: ha
  password: ha

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
