server:
   port: 10090


#security:
#  user:
#    password: geography

spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    database:
      platform: org.hibernate.dialect.MySQL5Dialect

info:
  app:
    name: GeographyService
    description: EHR platform json geography service.
    version: 1.0.0


---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@localhost:8761}/eureka/

---
spring:
  profiles: test
eureka:
  instance:
    ip-address: 172.19.103.73
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/


---
spring:
  profiles: prod
eureka:
  instance:
    ip-address: 11.1.2.21
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@11.1.2.21:8761}/eureka/


