server:
  port: ${svr-pack-analyzer.server.port}

info:
  app:
    name: SVR-PACK-ANALYZER
    description: EHR Platform Microservice.
    version: 1.0.0

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
  # REDIS
  redis:
    database: 0 # Database index used by the connection factory.
    timeout: 0 # Connection timeout in milliseconds.
    #sentinel:
    #  master: # Name of Redis server.
    #  nodes: # Comma-separated list of host:port pairs.
    pool:
      max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      max-wait: -1 # Maximum amount of time (in milliseconds) a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      min-idle: 1 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.

fast-dfs:
  connect-timeout: 10
  network-timeout: 60
  charset: ISO8859-1
  pool:
    init-size: 5
    max-size: 20
    wait-time: 500
  http:
    tracker-http-port: 80
    anti-steal-token: no
    secret-key: FastDFS1234567890

eip:
  tenant: jkzl

analyze:
  job:
    minSize: 10 #质控初始任务数
    maxSize: 10 #质控最大任务数
    cronExp: 0/1 * * * * ? #质控任务触发间隔表达式

quality:
  orgCode : jkzl #默认机构
  version: 59083976eebd #默认版本号
  cloud: medicalCloud #默认云平台code
  cloudName: 上饶医疗云 #默认云平台name

ehr:
  # 档案包数据提取器参数，从数据集中提取摘要、事件时间与身份标识
  require-data-sets:
    clinic:
      - HDSA00_01 #人口学信息
      - HDSD00_85 #门诊-挂号
      - HDSD00_73 #门诊-诊断记录
      - HDSD00_71 #门诊-费用汇总
      - HDSD00_70 #门诊-费用清单
    resident:
      - HDSA00_01 #人口学信息
      - HDSD00_13 #住院-入院记录
      - HDSD00_69 #住院-诊断记录
      - HDSD00_15 #住院-医嘱信息
      - HDSD00_68 #住院-费用汇总
      - HDSD00_67 #住院-费用清单
      - HDSD00_16 #住院-出院小结
    medicalExam:
      - HDSA00_01 #人口学信息
      - HDSB05_03 #体检-登记信息
      - HDSB05_81 #健康体检-项目子表
  pack-extractor:
    # 事件提取参数,用于生成事件摘要
    # 门诊从“门诊摘要”与“挂号”数据集提取事件
    # 住院从“病人摘要”，“入院记录”与“病案首页”提取事件 Clinic 0门诊 Resident 1住院  MedicalExam 2体检
    event:
      data-sets:
        - HDSC01_02: Clinic #门诊-挂号 v1.0
        - HDSD00_85: Clinic #门诊-挂号 v1.3
        - HDSC02_09: Resident #住院-入院记录 v1.0
        - HDSD00_13: Resident #住院-入院记录 v1.3
        - HDSD00_16: Resident #住院-出院小结 v1.3
        - HDSD00_11: Resident #住院-病案首页 v1.5
        - HDSB05_03: MedicalExam #体检-登记信息 v1.3
    #诊断信息
    diagnosis:
      data-sets:
        - HDSC01_03 #门诊-诊断记录 v1.0
        - HDSD00_73 #门诊-诊断记录 v1.3
        - HDSC02_17 #住院-诊断记录 v1.0
        - HDSD00_69 #住院-诊断记录 v1.3
        - HDSB05_84 #体检-诊断记录 v1.3
      code-meta-data:
        - HDSD00_01_550 #门诊-疾病临床诊断在特定分类体系中的代码 v1.0 & v1.3
        - HDSD00_69_002 #住院-疾病临床诊断在特定分类体系中的代码 v1.3
        - JDSB05_84_003 #体检-疾病临床诊断在特定分类体系中的代码 v1.3
      name-meta-data:
        - HDSD00_01_549 #门诊-疾病临床诊断在特定分类体系中的名称 v1.0 & v1.3
        - HDSD00_69_001 #住院-疾病临床诊断在特定分类体系中的名称 v1.3
        - JDSB05_84_004 #体检-疾病临床诊断在特定分类体系中的名称 v1.3
    #身份提取参数，从人口学提取
    identity:
      data-sets:
        - HDSA00_01 #人口学信息 v1.0 & v1.3
      meta-data:
        id-card-no: HDSA00_01_017 #身份证号码 v1.0 & v1.3
        id-card-type: HDSA00_01_016 #身份证类型 v1.0 & v1.3
        patient-name: HDSA00_01_009 #本人姓名 v1.3 (v1.0:HDSD00_01_002)
    #卡提取参数，从就诊摘要提取
    card:
      data-sets:
        - HDSC01_02 #门诊-挂号 v1.0
        - HDSD00_85 #门诊-挂号 v1.3
        - HDSC02_09 #住院-入院记录 v1.0
        - HDSD00_13 #住院-入院记录 v1.3
      card-num:
        - JDSD00_85_005 #门诊-就诊卡号 CARD_NUM
        - JDSD00_13_006 #住院-就诊卡号 CARD_NUM
      card-type:
        - JDSD00_85_006 #门诊-就诊卡类型 CARD_TYPE
        - JDSD00_13_007 #住院-就诊卡类型 CARD_TYPE
    #科室信息
    dept:
      data-sets:
        - HDSD00_85 #门诊-挂号 v1.3
        - HDSD00_13 #住院-入院记录 v1.3
      meta-data:
        - JDSD00_85_001 #门诊-就诊科室代码
        - JDSD00_13_004 #住院-入院科室编码

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.50:3306/healtharchive?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenweishan
    password: chenweishan
  redis:
    host: 172.19.103.47 # Redis server host.
    port: 6379
    password: redis!@456
  data:
    solr:
      zk-host: node1.hde.h3c.com,node2.hde.h3c.com,node3.hde.h3c.com:2181/solr
fast-dfs:
  tracker-server: 172.19.103.13:22122
  public-server: http://172.19.103.52
elasticsearch:
  cluster-name: elasticsearch
  cluster-nodes: 172.19.103.9:9300

