server:
  port: ${svr-workflow.server.port}

management:
  port: ${server.port}

info:
  app:
    name: WorkflowService
    description: EHR platform workflow service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
