server:
  port: 10240

management:
  port: ${server.port}

info:
  app:
    name: MedivalRecordsSvrApp
    description: MedivalRecordsSvrApp service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: alpha

---
spring:
  profiles: test

---
spring:
  profiles: prod
