endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    com:
      netflix: INFO

---
spring:
  profiles: dev

  thymeleaf:
    cache: false

server:
  ssl:
    key-store: C:/Windows/tomcat.keystore
    key-store-password: 123456
    key-password: 123456

eureka:
  instance:
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@localhost:8761}/eureka/

---
spring:
  profiles: sand-home-dev

  thymeleaf:
      cache: false

keystore:
  file: C:/Windows/tomcat.keystore
  password: 123456

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: test

keystore:
  file: /tomcat.keystore
  password: 123456

eureka:
  instance:
    ip-address: 192.168.131.151
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@192.168.131.151:8761}/eureka/

---
spring:
  profiles: prod

keystore:
  file: tomcat.keystore
  password: 123456

eureka:
  instance:
    ip-address: 11.1.2.21
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@11.1.2.21:8761}/eureka/