server:
  port: 4431

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  user:
    name: admin
    password: 123456

---
spring:
  profiles: dev

  thymeleaf:
    cache: false

keystore:
  file: C:/Windows/tomcat.keystore
  password: 123456

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: sand-home-dev

  thymeleaf:
      cache: false

keystore:
  file: C:/Windows/tomcat.keystore
  password: 123456

eureka:
  instance:
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: test

eureka:
  instance:
    ip-address: unknown
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/

---
spring:
  profiles: prod

eureka:
  instance:
    ip-address: unknown
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@127.0.0.1:8761}/eureka/