server:
  port: 10200

management:
  port: ${server.port}

---
spring:
  profiles: lincl

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 6000

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
