server:
  port: ${ag-ehr-platform.server.port}

management:
  port: ${server.port}

spring:
  metrics:
    export:
      statsd:
        host: 192.168.1.221
        port: 8125
        prefix: ag-ehr-platform

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
