server:
  port: ${ag-ehr-platform.server.port}

management:
  port: ${server.port}

zuul:
  ignored-services: "*"
  routes:
    svr-pack-mgr: /api/v1.0/packages
    svr-esb: /api/v1.0/esb/uploadLog

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
