server:
  port: ${svr-family.server.port}

management:
  port: ${server.port}

info:
  app:
    name: AppService
    description: EHR platform open service applicate administrative service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod

