server:
  port: 10070


info:
  app:
    name: OrganizationService
    description: EHR platform organization service.
    version: 1.0.0

spring:
 jpa:
  hibernate-dialect : org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@localhost:8761}/eureka/

---
spring:
  profiles: test
eureka:
  instance:
    ip-address: 172.19.103.73
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/


---
spring:
  profiles: prod

eureka:
  instance:
    ip-address: 172.19.103.73
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri:http://user:eureka@172.19.103.73:8761}/eureka/
