server:
  port: ${svr-organization.server.port}

management:
  port: ${server.port}

info:
  app:
    name: OrganizationService
    description: EHR platform organization service.
    version: 1.0.0

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: prod
